### ISSUE TITLE
Workshop on structuring R projects?

### ISSUE THREAD

**Issue by emjbishop** [BIGslu/CodeClub#4]
Now that I'm getting better with R I'm wondering what the best practices are for structuring and organizing my scripts. For example, I have to clean, load, analyze, and plot some data. Should I break these steps up into separate scripts? Should I source my functions or keep them in the main script?  Etc.

I'd like a workshop on how R professionals make these decisions and incorporate best practices. I've read about this a bit online (and could present what I've found if helpful) but would love to hear how people use these in the real world.

**Comment by DebbieLC** [comment]
Second this! Would be interested in a discussion around this topic.

**Comment by kdillmcfarland** [comment]
Scheduled for next week! Thanks for the topic suggestion!
